// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Free5GCSlice) DeepCopyInto(out *Free5GCSlice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Free5GCSlice.
func (in *Free5GCSlice) DeepCopy() *Free5GCSlice {
	if in == nil {
		return nil
	}
	out := new(Free5GCSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Free5GCSlice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Free5GCSliceList) DeepCopyInto(out *Free5GCSliceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Free5GCSlice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Free5GCSliceList.
func (in *Free5GCSliceList) DeepCopy() *Free5GCSliceList {
	if in == nil {
		return nil
	}
	out := new(Free5GCSliceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Free5GCSliceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Free5GCSliceSpec) DeepCopyInto(out *Free5GCSliceSpec) {
	*out = *in
	if in.SnssaiList != nil {
		in, out := &in.SnssaiList, &out.SnssaiList
		*out = make([]Snssai, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Free5GCSliceSpec.
func (in *Free5GCSliceSpec) DeepCopy() *Free5GCSliceSpec {
	if in == nil {
		return nil
	}
	out := new(Free5GCSliceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Free5GCSliceStatus) DeepCopyInto(out *Free5GCSliceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Free5GCSliceStatus.
func (in *Free5GCSliceStatus) DeepCopy() *Free5GCSliceStatus {
	if in == nil {
		return nil
	}
	out := new(Free5GCSliceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Snssai) DeepCopyInto(out *Snssai) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Snssai.
func (in *Snssai) DeepCopy() *Snssai {
	if in == nil {
		return nil
	}
	out := new(Snssai)
	in.DeepCopyInto(out)
	return out
}
